require "elrio/cap_inset_detector"
require "elrio/cli"
require "elrio/geometry"
require "elrio/image_optimizer"
require "elrio/pattern_detector"
require "elrio/point_size"
require "elrio/runner"
require "elrio/version"
